Replace window.setTimeout with just setTimeout
This is to fix the flaky test failures that cause:
Error: ReferenceError: window is not defined
 ❯ stopTimer src/composables/autoRefresh.ts:12:7
 ❯ startTimer src/composables/autoRefresh.ts:20:5
 ❯ executeAndResetTimer src/composables/autoRefresh.ts:31:7
 ❯ Timeout._onTimeout src/composables/autoRefresh.ts:22:7
 ❯ listOnTimeout node:internal/timers:588:17
 ❯ processTimers node:internal/timers:523:7