Frontend test warnings cleanup (#3074)
* Fix [Vue Router warn]: No match found for location with path <path> warnings in component tests

* Fix TypeError: textRange(...).getClientRects is not a function for all tests

* Fix AllowedRoutesStore test noise

* Fix useAuth test noise

* Cleanup various fetch noise in application tests

* Refactor ConfigurationStore so it doesn't fetch during construction and can be mocked correctly

* Refactor MessageStore so it doesn't fetch during construction and can be mocked correctly

* Clean up remaining  [Vue Router warn]: No match found for location with path warnings

* Added expected auth callback errors to what is being tested

* Mock oidc client to clean up Not implemented: navigation to another Document warnings

* Fix lint error

* CI tests run more slowly, so increase the slow test threshold to make it easier to identify failing tests.

* Remove extra spaces for the linter

* Properly await configurationStore.ensureLoaded() in App.vue watch

* Fix cve detected by audit